etc/dbus-serialbattery/bms/daly.py
this adds the battery production date to the hardware version  string. maybe somebody can make use of it to distinguish multiply dalys
=> read production date and append to hardware version

etc/dbus-serialbattery/bms/daly.py, etc/dbus-serialbattery/install-qml.sh, etc/dbus-serialbattery/qml/PageBatterySettings.qml
Change GUI widget to spin box 0-100. will be preset with the current SOC.
fix missing line in install-qml.sh for the settings page
=> make Reset SoC a spin box

etc/dbus-serialbattery/bms/daly.py
small fix, I found by the way.
A bad answer on writing SOC would crash the driver.
(never had it while developing with uart, but it fails very often with RS485/on a device with older FW)
=> Fix daly readsentence

etc/dbus-serialbattery/bms/daly.py
with the new cables I was able to sniff the rs485 traffic and found that in some cases (writing SOC to the bms) no data was actually written. So this was not the dalys fault but some behaviour of the RS485 converter (driver switching, I guess). It didn't happen with UART, just with RS485. 
Finally I added the same sleep that you already used for the request_data function, that you implemented to help another user who was having a lot read errors. This seems consistent as I remember he had a rs485 cable.
=> Fix daly rs485 write timing (write SOC problem)

etc/dbus-serialbattery/dbushelper.py
Interesting that there were no complaints to far. I've seen it quite some times that my battery gets full and lingers around with almost no current. So the time to go showed strange values then
=> fix meaningless time to go values

etc/dbus-serialbattery/bms/jkbms_can.py, etc/dbus-serialbattery/config.default.ini, etc/dbus-serialbattery/dbushelper.py, etc/dbus-serialbattery/reinstall-local.sh, etc/dbus-serialbattery/utils.py
My previouse change related to https://github.com/Louisvdw/dbus-serialbattery/issues/950 for JK bms can broke older "Black" JK bms devices. See fix in `jkbms_can.py`.
JK BMS cells are updating very slowly via can bus and cell count can be increased few times before all detected. This causes exception in `dbushelpre.py` at line `self._dbusservice[cellpath % (str(i + 1))] = voltage`. In the end the cell voltage values were missing and not updated in VenusOS. So I added option to preset cell count for JK CAN  `JKBMS_CAN_CELL_COUNT` which resolves the issue. Original logic is kept so the parameter is optional and not necessary if it works without. 
Last change in this PR fixes the reinstall shell script. It may happen that user has can2, but not can0 used by dbus-serialbattery. The original …
=> Fixing JK BMS black version.

etc/dbus-serialbattery/battery.py, etc/dbus-serialbattery/bms/jkbms_pb.py, etc/dbus-serialbattery/config.default.ini, etc/dbus-serialbattery/dbus-serialbattery.py
This pull request adds support for the JK BMS that is used in the EEL boxes.
Their Model Number start with PBxxxxx
I've tested this implimentation for about a week and it looks like it is running fine.
It misses propper CRC checking, but I was unable to find out the CRC algorithm in use.
There is only one non-zero byte at the end of the message and it is not following any
of the common CRC algorithms. So for now I rely on a fixed length and a header detection.
Thanks, JKW
=> adding support for JK BMS Model PDxxxx

etc/dbus-serialbattery/bms/eg4_ll.py
unique_identifier() is a function - change so logging display is correct
fix 'stanby' typo
=> fix: unique_identifier and typo

etc/dbus-serialbattery/bms/jkbms_ble.py, etc/dbus-serialbattery/bms/lltjbd_ble.py, etc/dbus-serialbattery/dbus-serialbattery.py
The same code was duplicated making things harder to read. This patch removes the duplicated code.
It also fixes en issue that could occur when a Bluetooth BMS was configured to be used but no address was given.
=> Moved some bluetooth specific code from each implementation to a common place

etc/dbus-serialbattery/bms/seplosv3.py, etc/dbus-serialbattery/dbus-serialbattery.py
Hi,
When running multiple BMS types over various addresses, I ran into an error whereby an unhandled exception is thrown: "RuntimeError: dictionary changed size during iteration". The cause for this exception was deleting 'None' values from the battery[] array in dbus-serialbattery.py. This causes the instance to crash and restart.
This happens when you specify multiple BMS to query, and specify multiple MODBUS_ADDRESSES in config.ini. If you have multiple BMS and various addresses, it is inevitable that a BMS/address combination that doesn't exist gets queried.
The main loop iterates all BMS for each address and stores an instance or None for that address. After that, the None-values get cleaned from the array while it's iterating it.
Note that the way this is built still only allows you …
=> Fixes for multi BMS on single USB-adapter

etc/dbus-serialbattery/bms/daren_485.py
Hi, 
For the Daren BMS, previously the low-soc alarm was the only dedicated alarm left, catched under a general purpose register and not yet identified. 
I've located the low soc and fuse_blown alarms from the dataset and implemented them on their dedicated alarm, instead of just triggering a general internal failure alarm. 
Over the last few days i managed to test the low soc alarm, and now the internal failure alarms are gone.
=> Improved Daren485 support for low_soc and fuse_blown protections

etc/dbus-serialbattery/bms/jkbms_pb.py
- the firmware version string was read one byte to short, showing only 15.1 instead of 15.19 
- temperature 3 is mirroring the MOSFET temp so it was removed to avoid charging current reduction based on wrong cell temperature reading (fixing https://github.com/mr-manuel/venus-os_dbus-serialbattery/issues/75)
=> Fixed Temp, added addition byte to version

dbus-serialbattery/bms/litime.py, dbus-serialbattery/bms/syncron_ble.py, dbus-serialbattery/dbus-serialbattery.py
Adding Litime BMS
LiTime is a battery brand that have their own BMS.
This a Bluetooth driver that is built on information gained from reverse engineering the LiTime battery app.
=> LiTime BMS

dbus-serialbattery/bms/jkbms_can.py
the voltage value from the CAN frame for the whole battery has only 1 decimal accuracy, so use the sum of the cell voltages to get 2 decimal accuracy
=> use sum of cell voltages instead of 1 decimal accuracy value from CAN

dbus-serialbattery/bms/eg4_lifepower.py
The reverse engineered EG4 LifePower protocol documentation mentioned that the high bit on cell voltages would ocassionally be set, possibly relating to a high power alarm: https://github.com/slim-bean/powermon?tab=readme-ov-file#group-1
Apparently the second highest bit can also be set sometimes, so that also needs to be masked out. Adjust the mask accordingly.
Fixes #155
=> Correct the mask on EG4 LifePower Cell voltages

dbus-serialbattery/battery.py
Avoid division by zero in get_midvoltage() according Issue #196
=> Avoid division by zero in get_midvoltage()

dbus-serialbattery/bms/jkbms_can.py, dbus-serialbattery/utils_can.py
Modified the code in utils_can that you can specify arbitration IDs wich are removed from cache after timeout with notification in the log.
This is neccessary for JK BMS who sent ALM_INFO 0x07F4 and BMSERR_INFO 0x18F328F4 only when alarm ocours. 
This will solve that the driver will stay with an alarm in an endless loop.
!!! Remember that the timer in last_error_time in jkbms_can.py is set to 120.0s. So if you want to a shorter time, reduce it.!!!
Its been tested now for 2 weeks without any issue. So it works stable.
=> CAN utils - Expire messages from cache

dbus-serialbattery/bms/jkbms_can.py, dbus-serialbattery/dbus-serialbattery.py, dbus-serialbattery/utils_can.py
All CAN frames will be cached for 5 seconds to guarantee that all values will be up to date ...
Frames older than 5 seconds will be removed from the cache, so that alarm frames for example fade out, if the alarm no longer exists
=> All received CAN frames will only be cached for 5 seconds

dbus-serialbattery/bms/daly_can.py
I am currently building a battery system with multiple differently sized batteries connected on one Can bus string. There's no way to set the battery capacities per individual battery. 
So this PR adds the ability for the Daly Can driver to read the BMS capacity setting and use that instead of the single user-provided value.
The code is running on my Cerbo GX Mk2 and works with two 100 Balance BMS (blue Daly BMS) daisy-chained together.
=> Set battery capacity from BMS in Daly Can

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/support_request.yml, CHANGELOG.md, dbus-serialbattery/bms/ubms_can.py, dbus-serialbattery/config.default.ini, dbus-serialbattery/dbus-serialbattery.py, dbus-serialbattery/utils.py
Hi, 
it took longer than anticipated but eventually I am done supporting the Valence U-BMS on can. There are still a number of things TODO where I believe some of them require upstream fixes. A significant difference to the BMS that are supported so far is, that the U-BMS supports multiple strings of modules of 4 cells each, e.g. a 4(x4)s2p config I have at home. That means it can not be assumed that the sum of the cell voltages equals the pack voltage. Each battery module features its own internal balancer. I did not dig deeper, but despite calculating the correct pack voltage, it is either ignored or overwritten upstream. In my case the cell voltage tab shows twice the voltage (becaue of 2 parallel strings), while the main menu overview correctly reports the self.voltage value that has …
=> added initial support for Valence U-BMS on CAN

dbus-serialbattery/dbus-serialbattery.py, dbus-serialbattery/standalone_helper.py, dbus-serialbattery/standalone_serialbattery.py
Update Standalone version to latest changes
=> Update standalone to latest version

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/support_request.yml, CHANGELOG.md, dbus-serialbattery/bms/ks48100.py, dbus-serialbattery/config.default.ini, dbus-serialbattery/dbus-serialbattery.py
So apparently PAPOOL switched either the supplier who they are sourcing complete battery modules from or the BMS manufacturer they are putting in their batteries.  The first batteries they shipped were Daren based but the newer batteries they are shipping now indicate:
INFO:SerialBattery:get_serial: CER2408-04
INFO:SerialBattery:set hardware_version: SNS01 16S100A Ho20-T1 02.02.01
Other notable differences are 2 RS485 ports and a third 485/CAN port. RJ45 Wiring pinout is slightly different to the older Daren BMS as well but they are cross compatible (share pins 1 and 7 commonality).  The OSD has changed as well:
I'm not sure if we should call these new bms SNS01, Ho20, or something else but for now this WIP PR proposes to add a new module which is fully working and based on the Daren485 …
=> Feature: add daren 485v2 / SNS01 BMS support

dbus-serialbattery/bms/jkbms_pb.py
Fixes the lenght of the serial number for JK BMS, to support multiple BMS where serial number is very sequencial
=> Fix serial number for jkbms pb

dbus-serialbattery/bms/daren_485.py
This PR fixes the command frame sent to Tian-Power BMS devices for telemetry retrieval.
According to the official [Tian-Power Communication Protocol v2.2.3](https://github.com/cpttinkering/daren-485/blob/main/Docs/BMS-BASEN_Energy-Storage-protocol-En.pdf.pdf) , section 5.1 (Table 5), the COMMAND INFO field (i.e., the fifth byte after CID2) is fixed to 0x01 for requesting real-time telemetry. It should not be derived from the device address or any external logic.
Reference:
“At this time, the specific COMMAND GROUP is fixed to 01H, indicating that the first group of battery telemetry data is acquired.”
This fix ensures protocol compliance and improves compatibility with Tian-Power BMS units.
=> Fix: Use fixed 0x01 for COMMAND INFO per Tian-Power BMS protocol 2.2.3
